//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCources.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cources
    {
        public int Id { get; set; }
        public string CourseTitle { get; set; }
        public int DayOfWeekId { get; set; }
        public int StartTime { get; set; }
        public int FinishTime { get; set; }
        public decimal Price { get; set; }
    
        public virtual DayOfWeek DayOfWeek { get; set; }
    }
}
