//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCources.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayOfWeek
    {
        public DayOfWeek()
        {
            this.Cources = new HashSet<Cources>();
        }
    
        public int Id { get; set; }
        public string DayOfWeekTitle { get; set; }
    
        public virtual ICollection<Cources> Cources { get; set; }
    }
}
